### ISSUE TITLE
this is possible do implementation for other coutries?

### ISSUE THREAD

**Issue by johnfelipe** [dracos/underground-live-map#10]
What i need to do, for create a demostration for my country?

**Comment by dracos** [comment]
Without an API returning live transport data, there is not a lot you can do.

You would need to:
* Find an API for your chosen mode of transport that gives you current position (either GPS or enough that you can work out approximate location, e.g. station information) of the individual vehicles;
* Write a script that converts that API output into the format needed by the code in this repository;
* Adapt the code in this repository to read from that file (it already does both London buses and Underground so hopefully is straightforward to adapt).

Hope that's helpful.
