### ISSUE TITLE
fetch.py error

### ISSUE THREAD

**Issue by JaRuleD** [dracos/underground-live-map#11]
which python version to use? there is many syntax error when running fetch.py
iam using python 3.8. thanks in advance

**Comment by dracos** [comment]
Umm, I wrote the script ten years ago, so it will be Python 2. I can't imagine it does anything that would be hard to migrate, though.

**Comment by JaRuleD** [comment]
Thank you for the reply. Your work has provided me with many inspirations and valuable references. I'm working on a similar project but it needs to show the movement of objects with realtime coordinates and not predictions.

**Comment by dracos** [comment]
Aww, thanks, glad it was of help :) Hopefully realtime would be a bit easier, you could drop all the code that tries to work out where things are, because you'd know! I'll hopefully get the script upgraded to python3 at some point.
